### PR TITLE
Unix directory fixes.

### PR DESCRIPTION
**Pull request by Geenz**
Just before we convert from Shift-JIS to UTF-8, this code will replace all occurrences of '\' with '/' on OS X and Linux.  I'm not sure if this should also apply to Windows.  This seems to resolve (most) file loading issues on OS X.  This does not include the retry code I previously committed.

### CODE REVIEW

**Comment by zardoru** [comment]
Hmm, to be honest, I'm not very fond of altering a character-conversion function for handling paths. I'd rather have a proper PathNormalize function that removes redundant slashes, replaces backslashes with forward slashes and removes illegal characters. This is achievable in about 3 lines or so.

**Comment by Geenz** [comment]
I'll deal with that when I get home. In the Directory class I assume?

**Comment by zardoru** [comment]
Yep.

**Comment by zardoru** [comment]
This should be fixed by now.

**Pull request closed without merging**
